apiVersion: v1
kind: Service
metadata:
  name: service-certreg
spec:
  type: NodePort
  selector:
    app: test-certreg
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30301
