apiVersion: apps/v1beta1
kind: Deployment
metadata: 
  name: nginx-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: test-nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nginx-pvc
      volumes:
      - name: nginx-pvc
        persistentVolumeClaim:
          claimName: gluster-pvc
