apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
subsets:
- addresses:
  - ip: 192.168.10.24
  ports:
  - port: 1
- addresses:
  - ip: 192.168.10.25
  ports:
  - port: 1
- addresses:
  - ip: 192.168.10.26
  ports:
  - port: 1
