apiVersion: v1
kind: Service
metadata:
  name: creg
spec:
  type: NodePort
  selector:
    app: certregister
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30001
