upstream ipam-forti {
    ip_hash;
    server 10.120.0.2:3007;
}

server {
    listen       80;
    server_name  sphw_reverse_proxy;
    client_max_body_size 300M;

    charset utf-8;
    access_log /dev/stdout main;
    error_log /dev/stderr warn;
#    error_log /dev/stderr debug;
#    rewrite_log on;

    location /ipam-books {
      alias /mnt/MC/books/riken-ipam-books;
    }
    location /rsscve {
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_pass http://rsscve;
    }
    location /docs {
      return 301 $scheme://$http_host/onestop;
    }
    location /cnlab-stdent2 {
      alias /mnt/MC/books/cnlab-stdent2-books;
    }
    location /onestop-doc {
      alias /mnt/MC/books/onestop-doc-books;
    }
    location /onestop {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        expires 0;
        alias /mnt/MC/books/onestop-books;
    }
    location /riken-mc {
      alias /mnt/MC/books/riken-mc-books;
    }
    location /assets {
      alias /mnt/MC/books/assets;
    }
    location /nict {
      alias /mnt/MC/books/nict-books;
    }
    location /juen {
      alias /mnt/MC/books/juen-books;
    }
    location /c2021_books {
      alias /mnt/MC/books/c2021_books;
    }
    location /riken {
      alias /mnt/MC/books/riken-books;
    }
    location / {
      return 301 $scheme://$http_host/ipam;
    }
}

