apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: test-nginx
spec:
  volumes:
  - name: nginx-volume
    hostPath:
      path: /mnt/MC/nginx
  containers:
  - name: nginx
    image: nginx:1.7.9
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: nginx-volume
