apiVersion: v1
kind: Pod
metadata:
  name: registry
  labels:
    app: docker-registry
spec:
  volumes:
  - name: registry-volume
    hostPath:
      path: /mnt/MC/registry-volume
  containers:
  - name: registry
    image: registry:2
    env:
    - name: REGISTRY_HTTP_TLS_CERTIFICATE
      value: /var/lib/registry/certs/my.crt
    - name: REGISTRY_HTTP_TLS_KEY
      value: /var/lib/registry/certs/my.key
    ports:
    - containerPort: 5000
    volumeMounts:
    - mountPath: /var/lib/registry
      name: registry-volume
