apiVersion: v1
kind: Service
metadata:
  name: service-registry
spec:
  type: NodePort
  selector:
    app: docker-registry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 32767
